### ISSUE TITLE
bioregistry.io is down on 2021-11-18

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioregistry-docker#2]
Currently getting `ERR_EMPTY_RESPONSE` when I visit https://bioregistry.io/ as of 2021-11-18T15:17:00Z

**Comment by cthoyt** [comment]
Hi @dhimmel sorry I was ill yesterday. Right now https://bioregistry.io/ looks good, but we will look into it and see if something funny happened

**Comment by dhimmel** [comment]
the server must have decided to get ill in solidarity with you! Feel free to close this if there's no way to figure out what happened.

**Comment by cthoyt** [comment]
Big mood. Hope the downtime didn't cause too much of a disruption :)
